### PR TITLE
fixed error in web key in GooglePlacesApi.java file

### PR DESCRIPTION
**Pull request by iamrishav**
@MayankGupta73

### CODE REVIEW

**Comment by MayankGupta73** [comment]
Hi 
Is the main change in the pull request changing
WEB_KEY = ctx.getString(R.string.google_maps_web_key);
to
WEB_KEY = ctx.getString(R.string.google_maps_key);

Have you used your own key for this?
If so I don't quite understand the reason for this pull request.

**Comment by iamrishav** [comment]
there is no field names "google_maps_web_key" in resource string file

**Comment by MayankGupta73** [comment]
Yes you need to create a keys.xml resource file and use your own Google Maps API key. There you can add a field  google_maps_web_key.
Or you can also do this in your strings.xml file but its safer to do this elsewhere.

**Comment by iamrishav** [comment]
can i refer to google_maps_api_xml fife instead of creating another file

**Comment by MayankGupta73** [comment]
No that file is for a different use.
You must create a new file app\src\main\res\values\keys.xml

It basically has the same structure as other resource files
`<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="google_maps_web_key">your_key_here</string>
</resources>`

Also if you are getting any errors related to admob you can just remove that otherwise you must also make an admob key and put it in this file as well.

**Pull request closed without merging**
